export {default as Pricing} from './pricing';
export {default as Car} from './car';
export {default as Charge} from './charge';
export {default as City} from './city';
export {default as Customers} from './customers';
export {default as Locations} from './locations';
export {default as Miles} from './miles';
export {default as Operator} from './operator';
export {default as Pickups} from './pickups';