import {Inter} from 'next/font/google';
import type {Metadata} from 'next';
import {Header} from '@app/components';
import headerData from '@app/data/header.json';
import './globals.css';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Dream Drive Rentals',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen bg-black text-white">
          <Header links={headerData} />
          {children}
        </main>
      </body>
    </html>
  );
}
